### PR TITLE
executables_db: add missing flags and ignore_errors kwargs

### LINKED ISSUE #137: Command brew which-update fails
I'm just added command-not-found tap and cannot run which-update:

```
% brew which-update
==> Using executables list from '/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/executables.txt'
Error: missing keywords: flags, ignore_errors
Warning: Removed Sorbet lines from backtrace!
/opt/homebrew/Library/Homebrew/formulary.rb:132:in `load_formula_from_path'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:64:in `block (2 levels) in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `block in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/which_update.rb:51:in `update_and_save!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/which-update.rb:41:in `which_update'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

Homebrew version:
```
% brew --version
Homebrew 4.1.17-33-g13ca5c3
Homebrew/homebrew-core (git revision ca924ee3875; last commit 2023-10-28)
Homebrew/homebrew-cask (git revision c9f9182d01; last commit 2023-10-27)
```

Command which-formula is working:
```
% brew which-formula identify
imagemagick
imagemagick@6
```

### PR DESCRIPTION
**Pull request by woodruffw**
This should fix #137.

### CODE REVIEW

**Comment by olfway** [comment]
Thanks, I tried to apply this change locally and got another error:
```
% brew which-update                                                                                                                                                                
==> Using executables list from '/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/executables.txt'
Error: undefined method `tap?' for Formulary::FormulaNamespacee10e006ff4e8e55a7544ada7893acdc4::A2ps:Class
Did you mean?  tap
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:67:in `block (2 levels) in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `block in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/which_update.rb:51:in `update_and_save!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/which-update.rb:41:in `which_update'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by woodruffw** [comment]
Whoops, looks like that was another vestigial API. Could you try again?

**Comment by olfway** [comment]
Sure, another error:
```
% brew which-update                                                                                                                                                                     
==> Using executables list from '/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/executables.txt'
Error: undefined method `full_name' for Formulary::FormulaNamespacee10e006ff4e8e55a7544ada7893acdc4::A2ps:Class
Did you mean?  full_names
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:68:in `block (2 levels) in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:63:in `block in update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `each'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/executables_db.rb:62:in `update!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/lib/which_update.rb:51:in `update_and_save!'
/opt/homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/which-update.rb:41:in `which_update'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by woodruffw** [comment]
Ugh, okay. Sorry for the continued pain here, I'll get an actual dev environment for this set up tonight.

**Comment by olfway** [comment]
Sure, thanks for your help!

**Comment by woodruffw** [comment]
Superseded.

**Pull request closed without merging**
