### PR TITLE
store short name directly in executables.txt

### PR DESCRIPTION
**Pull request by xu-cheng**
Per https://github.com/Homebrew/homebrew-command-not-found/commit/a5e5510318056381d050d9ebdde1b27828db3c5f

cc @bfontaine

### CODE REVIEW

**Comment by bfontaine** [comment]
:+1:

**Comment by xu-cheng** [comment]
May be worth for you to check I didn't accidentally break the script to update database file. Also I notice, there is an non-official tap formula(`jimbojsb/homebrew-launchrocket/launchrocket-plists:`) inside executables.txt. Is this intentional?

**Comment by bfontaine** [comment]
The script still works, sorry I pushed a conflicting commit when I updated the database, you should be able to fix it by applying this:

```
diff --git a/executables.txt b/executables.txt
index ae5e85e..f023b56 100644
--- a/executables.txt
+++ b/executables.txt
@@ -1656,7 +1656,7 @@ homebrew/science/gmt4:backtracker binlegs blockmean blockmedian blockmode dat2gm
 homebrew/science/grabix:grabix
 homebrew/science/h5utils:h5fromtxt h5topng h5totxt h5tovtk
 homebrew/science/harvest-tools:harvesttools
-homebrew/science/hdf5:gif2h5 h52gif h5c++ h5copy h5debug h5diff h5dump h5import h5jam h5ls h5mkgrp h5pcc h5perf h5perf_serial h5redeploy h5repack h5repart h5stat h5unjam ph5diff
+homebrew/science/hdf5:gif2h5 h52gif h5c++ h5cc h5copy h5debug h5diff h5dump h5import h5jam h5ls h5mkgrp h5perf_serial h5redeploy h5repack h5repart h5stat h5unjam
 homebrew/science/hmmer:alimask hmmalign hmmbuild hmmc2 hmmconvert hmmemit hmmerfm-exactmatch hmmfetch hmmlogo hmmpgmd hmmpress hmmscan hmmsearch hmmsim hmmstat jackhmmer makehmmerdb nhmmer nhmmscan phmmer
 homebrew/science/htsbox:htsbox
 homebrew/science/htslib:bgzip htsfile tabix
@@ -2074,6 +2074,7 @@ homebrew/x11/transmission-remote-gtk:transmission-remote-gtk
 homebrew/x11/wcm:wcm
 homebrew/x11/wmctrl:wmctrl
 homebrew/x11/x3270:x3270 x3270if
+homebrew/x11/xastir:callpass testdbfawk xastir xastir_udp_client
 homebrew/x11/xchat:xchat
 homebrew/x11/xdotool:xdotool
 homebrew/x11/xdu:xdu
@@ -4037,7 +4038,6 @@ xa:file65 ldo65 printcbm reloc65 uncpk xa
 xapian:copydatabase delve quest simpleexpand simpleindex simplesearch xapian-check xapian-chert-update xapian-compact xapian-config xapian-inspect xapian-metadata xapian-progsrv xapian-replicate xapian-replicate-server xapian-tcpsrv
 xar-mackyle:xar-mackyle
 xaric:xaric
-xastir:callpass testdbfawk xastir xastir_udp_client
 xbee-comm:xbfwup
 xcproj:xcproj
 xctool:xctool
```

Regarding the non-official tap formulae, this is ok for now, I still don’t know if I want to keep them or not. I’m affraid that we might get pull-requests for obscure taps if we officially support non-official taps.

**Comment by xu-cheng** [comment]
:ship:ed

**Comment by bfontaine** [comment]
Thank you :smile:

**Pull request merged**
