### PR TITLE
Setup git user for scheduled database updates

### PR DESCRIPTION
**Pull request by Rylan12**
Setup @BrewTestBot as the `git` user for the scheduled database updates.

Also, remove a debug line that I forgot to remove in #77

### CODE REVIEW

**Comment by Rylan12** [comment]
```
/usr/bin/git push origin master
fatal: could not read Username for 'https://github.com': Device not configured
```

Maybe a token issue? Let me try with `GITHUB_TOKEN`

**Comment by Rylan12** [comment]
```
/usr/bin/git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.        
To https://github.com/Homebrew/homebrew-command-not-found
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Homebrew/homebrew-command-not-found'
```

Different issue. I tried adding @BrewTestBot to be exempt from the branch protection rules but that didn't seem to work either. Let me try pushing to another, non-protected branch.

**Comment by Bo98** [comment]
I think you need to use `HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN` when pushing.

**Comment by Rylan12** [comment]
> I think you need to use `HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN` when pushing.
> 
> I've added it to this repo so you can give it a try.

Ugh, thanks. Yeah, that's what I was about to test out. Appreciate it ❤️

**Comment by Rylan12** [comment]
Hmm, okay. This PR wasn't supposed to be merged by @BrewTestBot...

It looks like it worked as expected, though: https://github.com/Homebrew/homebrew-command-not-found/commit/17b4ae8b146199d20a374a313db367aff7926173

**Comment by Bo98** [comment]
> I think it's because I ran it from the PR branch so the `actions/checkout` used that ref...?

Yeah it will have had all these commits checked out and then pushed them to master. Fast-forward merges (where the commit hashes don't change) are detected by GitHub as a PR merge, which is effectively what happened.

**Pull request merged**
